### ISSUE TITLE
报错batch-size 64 not multiple of GPU count 9 & 在设置GPU后, 训练代码会占用所有的GPU

### ISSUE THREAD

**Issue by jieruyao49** [wudashuo/yolov5#3]
当我训练时，会报以下错误:
`Traceback (most recent call last): File "/home/code/yolov5-master/train.py", line 522, in <module> device = select_device(opt.device, batch_size=opt.batch_size) File "/home/code/yolov5-master/utils/torch_utils.py", line 78, in select_device assert batch_size % n == 0, f'batch-size {batch_size} not multiple of GPU count {n}' 
AssertionError: batch-size 64 not multiple of GPU count 9`

为此我注释掉 untils/torch_utils.py文件中的以下两行：
if n > 1 and batch_size: # check that batch_size is compatible with device_count assert batch_size % n == 0, f'batch-size {batch_size} not multiple of GPU count {n}'

当我再运行时，将device设置为1，但最终会占用所有的gpu（linux系统中共有9个gpu，会被全部占用）

我的安装包如下所示：
_libgcc_mutex 0.1 main https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates 2021.1.19 h06a4308_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi 2020.12.5 py38h06a4308_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit 10.1.243 h6bb024c_0
ld_impl_linux-64 2.33.1 h53a641e_7 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi 3.3 he6710b0_2 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng 9.1.0 hdf63c60_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng 9.1.0 hdf63c60_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ncurses 6.2 he6710b0_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy 1.20.2
openssl 1.1.1k h27cfd23_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Pillow 8.2.0
pip 21.0.1 py38h06a4308_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python 3.8.8 hdb3f193_4 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
readline 8.1 h27cfd23_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools 52.0.0 py38h06a4308_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite 3.35.4 hdfb4753_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk 8.6.10 hbc83047_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torch 1.7.1+cu101
torchvision 0.8.2
typing-extensions 3.7.4.3
wheel 0.36.2 pyhd3eb1b0_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz 5.2.5 h7b6447c_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zlib 1.2.11 h7b6447c_3 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

absl-py 0.12.0
cachetools 4.2.1
certifi 2020.12.5
chardet 4.0.0
cycler 0.10.0
Cython 0.29.22
google-auth 1.28.1
google-auth-oauthlib 0.4.4
greenlet 1.0.0
grpcio 1.37.0
idna 2.10
kiwisolver 1.3.1
Markdown 3.3.4
matplotlib 3.3.4
mkl-fft 1.3.0
mkl-random 1.1.1
mkl-service 2.3.0
numpy 1.20.2
oauthlib 3.1.0
olefile 0.46
opencv-python 4.5.1.48
pandas 1.2.3
Pillow 8.2.0
pip 21.0.1
protobuf 3.15.8
pyasn1 0.4.8
pyasn1-modules 0.2.8
pycairo 1.19.1
pycocotools 2.0.2
pyparsing 2.4.7
python-dateutil 2.8.1
pytz 2021.1
PyYAML 5.4.1
reportlab 3.5.66
requests 2.25.1
requests-oauthlib 1.3.0
rsa 4.7.2
scipy 1.6.2
seaborn 0.11.1
setuptools 52.0.0.post20210125
six 1.15.0
SQLAlchemy 1.4.5
tensorboard 2.4.1
tensorboard-plugin-wit 1.8.0
thop 0.0.31.post2005241907
torch 1.7.1+cu101
torchvision 0.8.2
tornado 6.1
tqdm 4.60.0
typing-extensions 3.7.4.3
urllib3 1.26.4
Werkzeug 1.0.1
wheel 0.36.2

**Comment by wudashuo** [comment]
你的训练指令发一下。
得用`--device`指定一下训练所使用的GPU，batch size的大小应该是所用GPU的数量的整数倍。
不要注释掉那行代码，代码没错

**Comment by jieruyao49** [comment]
> 你的训练指令发一下。
> 得用`--device`指定一下训练所使用的GPU，batch size的大小应该是所用GPU的数量的整数倍。
> 不要注释掉那行代码，代码没错

我将注释的代码放开了，batch size改为63（共有9个gpu），指定device为1，指令如下：
python train.py --data /home/code/yolov5-master/data/coco128.yaml --cfg /home/code/yolov5-master/models/yolov5s.yaml --weights /home/code/yolov5-master/yolov5s.pt --batch-size 63 --device 1

训练仍出现占用所有GPU的情况
| NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 25%   45C    P2    49W / 250W |   1459MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 23%   28C    P8     7W / 250W |    725MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 23%   31C    P8     8W / 250W |    725MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:07:00.0 Off |                  N/A |
| 23%   31C    P8     7W / 250W |    725MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 23%   26C    P8     7W / 250W |    725MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:0B:00.0 Off |                  N/A |
| 23%   30C    P8     7W / 250W |    725MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  Off  | 00000000:0C:00.0 Off |                  N/A |
| 23%   41C    P2    54W / 250W |   1230MiB / 11178MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  Off  | 00000000:0D:00.0 Off |                  N/A |
| 23%   42C    P2    50W / 250W |    725MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   8  GeForce GTX 108...  Off  | 00000000:0E:00.0 Off |                  N/A |
| 23%   37C    P2    54W / 250W |    313MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     74342      C   python                                      1445MiB |
|    1     74342      C   python                                       711MiB |
|    2     74342      C   python                                       711MiB |
|    3     74342      C   python                                       711MiB |
|    4     74342      C   python                                       711MiB |
|    5     74342      C   python                                       711MiB |

**Comment by wudashuo** [comment]
1. 没有十足的把握不要修改代码。
2. 看显存使用情况，你复制的nvidia-smi这时候还没开始训练，是数据载入预处理阶段。
3. 我不知道你到底想用几块卡，你`--device 1 --batch 63`说明你把63个都放在了1号卡上训练，如果不加`--device`那就是默认0号卡，如果9块卡全用那就是`--device 0,1,2,3,4,5,6,7,8` 。记住batch必须能整除所用GPU的数量。
4. 如果还有问题就重置代码，在yolov5目录下`git reset --hard`。或者直接从原作者仓库下一个新的：`git clone https://github.com/ultralytics/yolov5.git`

**Comment by jieruyao49** [comment]
> 1. 没有十足的把握不要修改代码。
> 2. 看显存使用情况，你复制的nvidia-smi这时候还没开始训练，是数据载入预处理阶段。
> 3. 我不知道你到底想用几块卡，你`--device 1 --batch 63`说明你把63个都放在了1号卡上训练，如果不加`--device`那就是默认0号卡，如果9块卡全用那就是`--device 0,1,2,3,4,5,6,7,8` 。记住batch必须能整除所用GPU的数量。
> 4. 如果还有问题就重置代码，在yolov5目录下`git reset --hard`。或者直接从原作者仓库下一个新的：`git clone https://github.com/ultralytics/yolov5.git`

感谢你的回复，当我把代码更新到最新版本时，问题解决了。
